version: '3.9'

services:
  neo4j:
    image: neo4j:${NEO4J_VERSION}
    restart: unless-stopped
    environment:
      - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASSWORD}
      # DB and server
      - NEO4J_server_memory_pagecache_size=1G
      - NEO4J_server_memory_heap_initial__size=1G
      - NEO4J_server_memory_heap_max__size=2G
    ports:
      - 7687:7687
    volumes:
      - logs:/logs
      - data:/data
      - plugins:/plugins
      - import:/import

volumes:
  logs:
  data:
  plugins:
  import:
