services:
  explorer:
    image: kuzudb/explorer:latest
    restart: unless-stopped
    environment:
      - MODE=READ_ONLY
    ports:
      - 8000:8000
    volumes:
      - ./social_network:/database